theme: jekyll-theme-minimal
title: Let's Build a Simple Database
description: Writing a sqlite clone from scratch in Java
google_analytics: UA-143787397-1
collections:
  parts:
    output: true
defaults:
  - scope:
      path: ""
      type: parts
    values:
      layout: default
